# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20


#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20


# Main Menu --------------------------------------------------------------------------------

[[main]]
   pre = "linkedin"
   url = "https://www.linkedin.com/in/joseph-cai"
   identifier = "hM5WWYoueF"
   weight = 1



[[main]]
   name = "Home" #relative block icon
   pageRef = "/"
   identifier = "home"
   weight = 10

[[main]]
   name = "Blog"
   pageRef = "posts"
   identifier = "posts"
   weight = 20


# [[main]]
#    name = "Resource"
#    pageRef = "resource"
#    identifier = "lexicon"
#    weight = 30


[[main]]
   name = "SQL Report"
   parent="Featured"
   pageRef = "tags/sql"
   weight = 40

[[main]]
   name = "Financial Modelling"
   parent="Featured"
   pageRef = "tags/Financial-Modelling"
   weight = 42

# [[main]]
#    name = "ML-AI"
#    parent="Resource"
#    pageRef = "tags/ml-ai"
#    weight = 45
[[main]]
   name = "All Tags"
   parent="Featured"
   pageRef = "tags/"
   weight = 45

[[main]]
   name = "About"
   # parent="About"
   pageRef = "about/about-no-arbitrage"
   identifier = "about"
   weight = 90

# [[main]]
#    name = "Author"
#    parent="About"
#    pageRef = "about/about-author"
#    identifier = "author"
#    weight = 100


# Icon Group --------------------------------------------------------------------------------


# [[main]]
#    identifier = "web"
#    pre = "link"
#    url = "https://hello.no-arbitrage.com"
#    weight = 200





#  Footer --------------------------------------------------------------------------------


[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 810

[[footer]]
   name = "⇱Connect"
   url = "https://hello.no-arbitrage.com"
   weight = 820
# [[footer]]
#    name = "Interview Guide"
#    pageRef = "interview"
#    weight = 14
[[footer]]
   pre = "github"
   url = "https://github.com/no-arbitrage/no-arbitrage.github.io/"
   identifier = "cpbxL6BzBj"
   weight = 880
