# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[main]]
name = "Home" #relative block icon
pageRef = "/"
identifier = "home"
weight = 1

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "posts"
weight = 2

[[main]]
  identifier = "web"
  pre = "link"
  url = "https://hello.no-arbitrage.com"
  weight = 40

# [[main]]
# name = "Featured"
# parent = "Blog"
# pageRef = ""
# identifier = "feat-posts"
# weight = 21

# [[main]]
# name = "Latest"
# parent = "Blog"
# pageRef = ""
# identifier = "latest-posts"
# weight = 22

# [[main]]
# name = "Showcase"
# pageRef = "portfolio"
# identifier = "portfolio"
# weight = 4

[[main]]
name = "Lexicon"
pageRef = "resource"
identifier = "lexicon"
weight = 6

[[main]]
name = "About"
pageRef = "about"
identifier = "about"
weight = 7

[[main]]
pre = "github"
url = "https://github.com/no-arbitrage/no-arbitrage.github.io/"
identifier = "cpbxL6BzBj"
weight = 10

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/joseph-cai"
identifier = "hM5WWYoueF"
weight = 12

# [[main]]
# pre = "codepen"
# pageRef = "/"
# identifier = "p2788GrnVn"
# weight = 9

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 13
[[footer]]
   name = "⇱Connect"
   url = "https://connect.no-arbitrage.com"
   weight = 15
# [[footer]]
#    name = "Interview Guide"
#    pageRef = "interview"
#    weight = 14
