colorScheme = "Slate"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
highlightCurrentMenuArea = true
math = true
 
mainSections = [ "posts" ]
backgroundImageWidth = 1200
defaultBackgroundImage = "/img/background.svg"

[header]
  layout = "fixed-gradient"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true
  defaultFeaturedImage = "/img/lavalamp.svg"
  defaultBackgroundImage = "/img/background.svg"
  homepageImage = "/img/background.svg"

[article]
  showDate = true
  # showViews = true
  showLikes = true
  showDateUpdated = false
 
  showComments = true
  showAuthor = true
  showHero = true
  layoutBackgroundHeaderSpace = true
  heroStyle = "background"   #basic, big, background, thumbAndBackground
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
   
  showAuthorBottom = true
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = true
  showZenMode = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background"
  defaultBackgroundImage = "/img/background.svg"
   
  layoutBackgroundBlur = true
   
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background"  
  defaultBackgroundImage = "/img/lavalamp.svg"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[firebase]
  apiKey	= "AIzaSyC1NmU4Xj1S6QS7YNOfKNaQch-bSlub6qA"                 
  authDomain	= "no-arbitrage.firebaseapp.com"             
  projectId	 = "no-arbitrage"                              
  storageBucket	 ="no-arbitrage.firebasestorage.app"      
  messagingSenderId= "566087795243"  
  appId	  =  "1:566087795243:web:191196a79d31b80dba606e"               
  measurementId	   = "G-P0D0SQXP9F"  
  
       
[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]



# // Import the functions you need from the SDKs you need
# import { initializeApp } from "firebase/app";
# import { getAnalytics } from "firebase/analytics";
# // TODO: Add SDKs for Firebase products that you want to use
# // https://firebase.google.com/docs/web/setup#available-libraries
# 
# // Your web app's Firebase configuration
# // For Firebase JS SDK v7.20.0 and later, measurementId is optional
# const firebaseConfig = {
#   apiKey: "AIzaSyC1NmU4Xj1S6QS7YNOfKNaQch-bSlub6qA",
#   authDomain: "no-arbitrage.firebaseapp.com",
#   projectId: "no-arbitrage",
#   storageBucket: "no-arbitrage.firebasestorage.app",
#   messagingSenderId: "566087795243",
#   appId: "1:566087795243:web:191196a79d31b80dba606e",
#   measurementId: "G-P0D0SQXP9F"
# };
# 
# // Initialize Firebase
# const app = initializeApp(firebaseConfig);
# const analytics = getAnalytics(app);

